pipeline:
  setup:
    image: alpine:latest
    commands:
      - apk add git
      - mkdir -p subprojects && cd subprojects
      - git clone https://codeberg.org/dnkl/tllist.git
      - cd ..

  codespell:
    image: alpine:latest
    commands:
      - apk add python3
      - apk add py3-pip
      - pip install codespell
      - codespell README.md CHANGELOG.md *.c *.h fcft/*.h doc/*.scd

  x64:
    group: build
    image: alpine:latest
    commands:
      - apk update
      - apk add musl-dev linux-headers meson ninja gcc scdoc
      - apk add pixman-dev freetype-dev fontconfig-dev harfbuzz-dev
      - apk add utf8proc-dev wayland-dev wayland-protocols
      - apk add git
      - apk add check-dev
      - apk add ttf-hack font-noto-emoji

      # Debug
      - mkdir -p bld/debug-x64
      - cd bld/debug-x64
      - meson --buildtype=debug -Dtext-shaping=enabled -Dtest-text-shaping=true -Dexamples=true ../..
      - ninja -v -k0
      - ninja -v test
      - cd ../..

      # Release
      - mkdir -p bld/release-x64
      - cd bld/release-x64
      - meson --buildtype=release -Dtext-shaping=enabled  -Dtest-text-shaping=true -Dexamples=true ../../
      - ninja -v -k0
      - ninja -v test
      - cd ../..

      # no text shaping
      - apk del harfbuzz harfbuzz-dev
      - mkdir -p bld/debug-x64-no-text-shaping
      - cd bld/debug-x64-no-text-shaping
      - meson --buildtype=debug -Dtext-shaping=disabled -Dtest-text-shaping=false ../..
      - ninja -v -k0
      - ninja -v test
      - cd ../..

  x86:
    group: build
    image: i386/alpine:latest
    commands:
      - apk update
      - apk add musl-dev linux-headers meson ninja gcc scdoc
      - apk add pixman-dev freetype-dev fontconfig-dev harfbuzz-dev
      - apk add utf8proc-dev wayland-dev wayland-protocols
      - apk add git
      - apk add check-dev
      - apk add ttf-hack font-noto-emoji

      # Debug
      - mkdir -p bld/debug-x86
      - cd bld/debug-x86
      - meson --buildtype=debug -Dtext-shaping=enabled  -Dtest-text-shaping=true -Dexamples=true ../..
      - ninja -v -k0
      - ninja -v test
      - cd ../..

      # Release
      - mkdir -p bld/release-x86
      - cd bld/release-x86
      - meson --buildtype=release -Dtext-shaping=enabled  -Dtest-text-shaping=true -Dexamples=true ../../
      - ninja -v -k0
      - ninja -v test
      - cd ../..
